### ISSUE TITLE
bug: TypeError: unsubscribe is not a function

### ISSUE THREAD

**Issue by OxMarco** [waku-org/waku-react#47]
The following codebase

```typescript
 const contentTopic = "/test/test/test/test";
const encoder = createEncoder({ contentTopic, ephemeral: true });
const decoder = createDecoder(contentTopic);
const { node, error, isLoading } = useWaku();
const { messages: filterMessages } = useFilterMessages({ node, decoder });
const { push } = useLightPush({ node, encoder });

useEffect(() => {
  console.log(
    filterMessages.map((wakuMessage) => {
      console.log("wakuMessage", wakuMessage);
      if (!wakuMessage.payload) return;
      return ChatMessage.decode(wakuMessage.payload);
    })
  );
}, [filterMessages]);
```

triggers the following error

```
TypeError: unsubscribe is not a function
    at useFilterMessages.ts:74:7
    at safelyCallDestroy (chunk-4YFJ7OCR.js:23637:13)
    at commitHookEffectListUnmount (chunk-4YFJ7OCR.js:23764:19)
    at commitPassiveUnmountOnFiber (chunk-4YFJ7OCR.js:25121:17)
    at commitPassiveUnmountEffects_complete (chunk-4YFJ7OCR.js:25102:15)
    at commitPassiveUnmountEffects_begin (chunk-4YFJ7OCR.js:25093:15)
    at commitPassiveUnmountEffects (chunk-4YFJ7OCR.js:25058:11)
    at flushPassiveEffectsImpl (chunk-4YFJ7OCR.js:26378:11)
    at flushPassiveEffects (chunk-4YFJ7OCR.js:26336:22)
    at chunk-4YFJ7OCR.js:26217:17
```

**Comment by weboko** [comment]
hi @OxMarco, I will look into and provide fix for this bug this / next week

**Comment by weboko** [comment]
@OxMarco can you try `@waku/react@0.0.7-35b3583` or `latest`? If anything - ping me - I will fix.

**Comment by OxMarco** [comment]
mmm no

I now get plenty of errors like

```
✘ [ERROR] No matching export in "node_modules/protons-runtime/dist/src/index.js" for import "MaxLengthError"

    node_modules/@waku/proto/dist/generated/filter.js:6:39:
      6 │ import { decodeMessage, encodeMessage, MaxLengthError, message } from 'protons-runtime';
        ╵               
```

in my *package.json* file I have

`"@waku/react": "^0.0.7-35b3583"`
